import banach_spaces_continuous_differentiable_analytic_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace banach_spaces_continuous_differentiable_analytic_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end banach_spaces_continuous_differentiable_analytic_lemma_canonical_lane_mathlib
end HautevilleHouse
